name: scraper-hourly

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      API_TOKEN: ${{ secrets.GOOGLE_API_KEY }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run scraper
      run: python scraper.py $API_TOKEN
    - name: Commit CSVs
      run: |
        git config --global user.name 'Bot'
        git config --global user.email 'tigerjwang@users.noreply.github.com'
        git add .
        git diff-index --quiet HEAD || git commit -m "(Bot) Run scraper"
        git push
